name = "pevensie_redis"
version = "1.0.0"
description = "The official Redis-compatible driver for the Pevensie framework"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "pevensie_redis" }
links = [{ title = "Website", href = "https://pevensie.dev" }]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
radish = ">= 0.15.0 and < 1.0.0"
pevensie = ">= 1.0.0 and < 2.0.0"
mug = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
bath = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
